# PyInstaller spec for the Arcana desktop build.
#
#   .venv-pack\Scripts\pyinstaller installer\arcana.spec --noconfirm
#
# Build from an environment with the CPU-only torch: the CUDA build is 4.4 GB
# against 421 MB, and searching never needs a GPU. Indexing and story mode are
# slower without one, which is the documented trade for a shippable download.
#
# onedir, not onefile, on purpose: onefile unpacks a multi-gigabyte archive to a
# temp directory on every launch. onedir starts immediately and is what an
# installer wants anyway.

import os
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

BLOCK_CIPHER = None
ROOT = os.path.abspath(os.getcwd())

# ── one version, read from the package ───────────────────────────────────────
# pyproject.toml and installer/arcana.iss used to carry their own copies, and
# they had already drifted (0.1.0 against 0.2.0). Everything now reads
# arcana/__init__.py, and this writes the Inno half of that chain.
_ns = {}
with open(os.path.join(ROOT, "arcana", "__init__.py"), encoding="utf-8") as _fh:
    exec(compile(_fh.read(), "arcana/__init__.py", "exec"), _ns)
VERSION = _ns["__version__"]

ICON = os.path.join(ROOT, "arcana", "assets", "arcana.ico")
if not os.path.exists(ICON):                                 # pragma: no cover
    print("[spec] WARNING: arcana.ico missing; the build gets the default icon.")
    ICON = None

# The Windows version resource for the frozen executable. Without it the file
# properties show a blank version, which reads as an unfinished build.
_parts = (VERSION.split(".") + ["0", "0", "0", "0"])[:4]
_nums = ", ".join(str(int(p)) if p.isdigit() else "0" for p in _parts)
_verfile = os.path.join(ROOT, "installer", "file_version_info.txt")
with open(_verfile, "w", encoding="utf-8") as _fh:
    _fh.write(f"""VSVersionInfo(
  ffi=FixedFileInfo(filevers=({_nums}), prodvers=({_nums}), mask=0x3f, flags=0x0,
                    OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)),
  kids=[
    StringFileInfo([StringTable('040904B0', [
      StringStruct('CompanyName', 'Antoine Bellemare'),
      StringStruct('FileDescription', 'Arcana'),
      StringStruct('FileVersion', '{VERSION}'),
      StringStruct('InternalName', 'Arcana'),
      StringStruct('OriginalFilename', 'Arcana.exe'),
      StringStruct('ProductName', 'Arcana'),
      StringStruct('ProductVersion', '{VERSION}')])]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
""")

# The Inno half of the chain: arcana.iss #includes this.
with open(os.path.join(ROOT, "installer", "version.iss"), "w", encoding="utf-8") as _fh:
    _fh.write("; Generated by arcana.spec at build time -- do not edit.\n")
    _fh.write('#define AppVersion "' + VERSION + '"\n')
print(f"[spec] building Arcana {VERSION}")

# ── data files ────────────────────────────────────────────────────────────────
datas = [
    # Dash serves assets/custom.css from the package directory; without it every
    # input renders white-on-white. db.py reads assets/labels_*.txt for cluster
    # naming. Neither is a .py file, so nothing collects them automatically.
    (os.path.join(ROOT, "arcana", "assets"), os.path.join("arcana", "assets")),
]

# ModFlows source is NOT bundled, deliberately.
#
# The upstream at github.com/maria-larchenko/modflows has no LICENSE, so
# default copyright applies and there is no right to redistribute it. Builds
# before 5 September 2026 shipped five of its files inside _internal/modflows.
# See LICENSING.md, item A0.
#
# arcana/modflows_net.py is our own implementation of the same inference path
# and ships as ordinary package code. It is verified against the checkpoint
# with strict state_dict loading and produces bit-identical output to what it
# replaced; see tests/test_modflows_net.py.
#
# The 229 MB checkpoint still does not ship: it is MIT, and downloaded once
# into the user's writable data directory on first use, which is also the only
# place it could survive a reinstall.
for pkg in ("dash", "dash_daq", "plotly", "librosa", "usearch"):
    try:
        datas += collect_data_files(pkg)
    except Exception as e:                                   # pragma: no cover
        print(f"[spec] WARNING: no data files collected for {pkg}: {e}")

# ── imports PyInstaller's static analysis cannot see ──────────────────────────
# Everything here is imported inside a function, behind a try/except, or by
# string. Verified by walking the AST of arcana/*.py for non-module-scope
# imports; see docs/hardening-audit.md.
hiddenimports = [
    # our own modules, several of which are only imported lazily
    "arcana.arcana", "arcana.db", "arcana.bundle", "arcana.legacy",
    "arcana.relocate", "arcana.paths", "arcana.cvio",
    "arcana.palette", "arcana.style", "arcana.color_transfer", "arcana.lab_transfer",
    # Added after the first draft of this spec. models/jobs/ui_* are reached
    # from arcana.py at module scope, but refselect, folderpicker and envcheck
    # are imported inside functions and would otherwise be dropped -- taking
    # the colour-range panel and the Browse button with them.
    "arcana.models", "arcana.jobs", "arcana.envcheck", "arcana.folderpicker",
    "arcana.ui_datasets", "arcana.ui_style", "arcana.refselect",
    # scientific bits reached only from inside functions
    "sklearn.decomposition", "sklearn.manifold", "sklearn.cluster", "sklearn.metrics",
    "scipy.special.cython_special",
    "ot",                       # POT, used for palette EMD
    # media
    "PIL.PngImagePlugin", "PIL.WebPImagePlugin", "PIL.JpegImagePlugin",
    "soundfile", "librosa", "numba",
    # arcana/modflows_net.py builds its encoder from torchvision and resizes
    # with transforms.v2. Those are reachable by analysis now that it is
    # ordinary package code rather than bundled data, but naming them costs
    # nothing and survives a refactor that hides the import.
    "torchvision", "torchvision.transforms", "torchvision.transforms.v2",
    # models
    "usearch.index",
    "transformers", "transformers.models.clip", "transformers.models.clap",
    "diffusers", "diffusers.pipelines.stable_diffusion",
    # dash component libraries register themselves at import
    "dash_daq",
]
hiddenimports += collect_submodules("dash")

# ── what we deliberately leave out ───────────────────────────────────────────
excludes = [
    "tkinter",          # nothing in the app uses it
    "pytest", "pyflakes", "mypy", "ruff",
    "IPython", "jupyter", "notebook",
    # NOT torch.distributed: torch/utils/data/dataloader.py imports it
    # unconditionally, so excluding it fails at `import torch` with
    # ModuleNotFoundError. Same reasoning for torch.testing -- leave torch
    # alone and let its own PyInstaller hook decide what is reachable.
]

a = Analysis(
    [os.path.join(ROOT, "installer", "launcher.py")],
    pathex=[ROOT],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=BLOCK_CIPHER,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=BLOCK_CIPHER)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Arcana",
    icon=ICON,
    version=_verfile,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,          # UPX corrupts some numpy/torch DLLs
    # Keep the console for the spike: a windowed build hides the traceback that
    # tells you what is missing. Flip to console=False once it launches clean.
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    # The GPU build goes to dist/Arcana-GPU so both variants can exist side by
    # side without one overwriting the other's 900 MB. The executable inside is
    # still Arcana.exe either way -- only the staging folder differs, and
    # arcana.iss picks the matching one from its own /DGpu flag.
    name=("Arcana-GPU" if os.environ.get("ARCANA_BUILD_VARIANT", "").upper() == "GPU"
          else "Arcana"),
)
